### ISSUE TITLE
Add GET /safes/{safe_address} route

### ISSUE THREAD

**Issue by fmrsabino** [5afe/safe-client-gateway-nest#115]
Transaction Service dependencies:
- [x] `/v1/safes/{}/` https://github.com/5afe/safe-client-gateway-nest/pull/116
- [x] `/v1/about/master-copies/` https://github.com/5afe/safe-client-gateway-nest/issues/98
- [x] `/v1/contracts/{}/` https://github.com/5afe/safe-client-gateway-nest/issues/100
- [x] `/v1/safes/{}/transfers/` https://github.com/5afe/safe-client-gateway-nest/issues/125
- [x] `/v1/safes/{}/multisig-transactions/` https://github.com/5afe/safe-client-gateway-nest/issues/126
- [x] `/v1/safes/{}/all-transactions/` https://github.com/5afe/safe-client-gateway-nest/issues/127

Config Service dependencies:
- [x] `/v1/chains/{}/`

**Comment by fmrsabino** [comment]
This route requires the `master-copies` endpoint to be implemented and available in the domain which is currently part of https://github.com/5afe/safe-client-gateway-nest/issues/98.

Support for getting a specific Safe from the domain layer was added here: https://github.com/5afe/safe-client-gateway-nest/pull/116

**Comment by fmrsabino** [comment]
Blocked by https://github.com/5afe/safe-client-gateway-nest/issues/125 https://github.com/5afe/safe-client-gateway-nest/issues/126 and https://github.com/5afe/safe-client-gateway-nest/issues/127
